#
# Copyright (c) 2025. Oliver Froberg
#
# This code is licensed under the GNU Lesser General Public License v3.0
# See: https://www.gnu.org/licenses/lgpl-3.0-standalone.html
#

org.gradle.jvmargs = -Xmx4G
org.gradle.parallel = true
fabric.loom.multiProjectOptimisation = true

javaVersion = 21
buildFor = fabric, neoforge
mcVersion = 1.21.10

modVersion = 0.14.0-DEV.1
modId = fallingtrees
modGroup = dev.pandasystems

modName = Panda's Falling Trees
modDescription = Makes trees fall realistically.
modAuthors = The Panda Oliver
modLicense = GNU GPLv3

# Loader versions
fabricLoaderVersion = 0.17.3
neoforgeLoaderVersion = 21.10.16-beta

# Parchment mapping
parchmentMinecraftVersion = 1.21.9
parchmentMappingsVersion = 2025.10.05

# Dependencies
fabricApiVersion = 0.135.0+1.21.10
pandalibVersion = 1.0.0-86+mc1.21.10