#
# Copyright (c) 2025. Oliver Froberg
#
# This code is licensed under the GNU Lesser General Public License v3.0
# See: https://www.gnu.org/licenses/lgpl-3.0-standalone.html
#

org.gradle.jvmargs = -Xmx4G
org.gradle.parallel = true
org.gradle.caching = true
fabric.loom.multiProjectOptimisation = true

javaVersion = 21
buildFor = fabric, neoforge
mcVersion = 1.21.4

modVersion = 0.14.0
modId = fallingtrees
modGroup = dev.pandasystems

modName = Panda's Falling Trees
modDescription = Makes trees fall realistically.
modAuthors = The Panda Oliver
modLicense = GNU GPLv3

# Loader versions
fabricLoaderVersion = 0.16.14
neoforgeLoaderVersion = 21.4.141

# Parchment mapping
parchmentMinecraftVersion = 1.21.4
parchmentMappingsVersion = 2025.03.23

# Dependencies
fabricApiVersion = 0.119.4+1.21.4
pandalibVersion = 1.0.0+1.21.4-152