org.gradle.jvmargs = -Xmx4G
java_version = 21

#### Minecraft ####

minecraft_version = 1.21.8
supported_mod_loaders = fabric,neoforge

fabric_version = 0.16.9
fabric_api_version = 0.131.0+1.21.8
fabric_version_range = >=1.21.8 <1.22

neoforge_version = 21.8.25
neoforge_version_range = [1.21.8,1.22)

parchment_minecraft_version = 1.21.8
parchment_version = 2025.07.20

#### Mod ####

maven_group = me.pandamods

mod_id = fallingtrees
mod_version = 0.13.3

mod_name = Panda's Falling Tree's
mod_description = Makes trees fall realistically.
mod_author = The Panda Oliver
mod_license = GPL-3

#### Project ####

project_curseforge_id = 880630
project_curseforge_slug = pandas-falling-trees
project_modrinth_id = i2kUe4lq
project_modrinth_slug = pandas-falling-trees
project_github_repo = PandaMods-Dev/Pandas-Falling-Trees

## publishing ##
publishing_dry_run = false

publishing_minecraft_version = 1.21.4

# Uncomment the next line to publish to versions in the range of 'publishing_minecraft_version'
# and 'publishing_latest_minecraft_version'
#publishing_latest_minecraft_version = 1.21.4

# 0 = STABLE | 1 = BETA | 2 = ALPHA
publishing_release_type = 1

#### Mods Dependencies ####
deps_modmenu_version = 13.0.0
deps_pandalib_version = mc1.21.8-1.0.0-DEV.4