[versions]
kotlin = "2.1.21"
minecraft = "1.21.8"
pandalib = "mc1.21.8-1.0.0-DEV.10"

[plugins]
ideaExt = { id = "org.jetbrains.gradle.plugin.idea-ext", version = "1.1.10" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version = "8.3.6" }
modPublish = { id = "me.modmuss50.mod-publish-plugin", version = "0.8.4" }
grabver = { id = "eu.davidea.grabver", version = "2.0.3" }
architecturyPlugin = { id = "architectury-plugin", version = "3.4-SNAPSHOT" }
architecturyLoom = { id = "dev.architectury.loom", version = "1.10-SNAPSHOT" }

[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
parchment = { group = "org.parchmentmc.data", name = "parchment-1.21.8", version = "2025.07.20" }
fabricLoader = { group = "net.fabricmc", name = "fabric-loader", version = "0.16.14" }
fabricApi = { group = "net.fabricmc.fabric-api", name = "fabric-api", version = "0.131.0+1.21.8" }
neoforgeLoader = { group = "net.neoforged", name = "neoforge", version = "21.8.25" }
modmenu = { group = "com.terraformersmc", name = "modmenu", version = "15.0.0-beta.3" }
pandalib-common = { group = "dev.pandasystems", name = "pandalib", version.ref = "pandalib" }
pandalib-fabric = { group = "dev.pandasystems", name = "pandalib-fabric", version.ref = "pandalib" }
pandalib-neoforge = { group = "dev.pandasystems", name = "pandalib-neoforge", version.ref = "pandalib" }
